### ISSUE TITLE
Issue : Channel not responding

### ISSUE THREAD

**Issue by aj031679** [TehCrucible/G2Gfm.bundle#6] opened 2015-07-08 01:18 UTC
Issue : Channel not responding while playing on pc (Windows) or Roku 3 anyone else having this problem.

Thanks

**Comment by agp94** [comment] 2015-07-09 11:18
Same here.

**Comment by billbo10** [comment] 2015-07-09 14:36
The problem is g2g.fm was taken down! i believe they are up and running again but with a new domain name.  need software tech to adjust the code for new site

**Comment by agp94** [comment] 2015-07-09 14:41
http://moviez.se/ is the new domain. But I copy-pasted the g2g.fm url that you use in the plug-in and it was correctly redirected!. After the redirect I was on the page of the series that i had chosen

**Comment by billbo10** [comment] 2015-07-09 14:43
agp94 are you saying you have it working?

**Comment by agp94** [comment] 2015-07-09 14:47
No, I'm saying that manually it worked. I just that the problem wasn't the domain but obviously you know the situation better than me.

**Comment by billbo10** [comment] 2015-07-09 14:49
ah right must be something else stopping it!
back to downloading tv series until it gets fixed

**Comment by agp94** [comment] 2015-07-09 14:53
I think that this plug-in works only when there is a google drive link in the list.

**Comment by billbo10** [comment] 2015-07-12 18:22
I followed info on another site and changed the 3-4 occurrences of  4o.se to moviez.se and it seems to be working

**Comment by aj031679** [comment] 2015-07-12 18:34
thanks it's working for me
 
Date: Sun, 12 Jul 2015 11:22:16 -0700

**Comment by Axxel6307** [comment] 2015-07-13 22:07
Do you know if it will be updated for the roku?  Or is there way to manually fix that?

**Comment by Axxel6307** [comment] 2015-07-13 22:11
aj031679,  how did you get g2g back up on your roku 3? Can you send me link to instructions? I don't know what change 3 4 occurrence of 40.se means....

**Comment by TehCrucible** [comment] 2015-07-13 23:27
Fixed now.  Thanks agp94 for the new url.  To update, you'll need to re-install as per the instructions in the readme.  Be sure to restart your Plex server after overwriting the files.

**Closed by TehCrucible** 2015-07-13 23:27 UTC
